[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[edge_functions]]
  function = "dify-stream"
  path = "/.netlify/functions/dify-stream"

[[edge_functions]]
  function = "azure-tts"
  path = "/.netlify/functions/azure-tts"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200


