[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[edge_functions]]
  function = "dify-stream"
  path = "/.netlify/functions/dify-stream"

[[edge_functions]]
  function = "azure-tts"
  path = "/.netlify/functions/azure-tts"

# 明确声明 Edge Functions 使用 Deno 环境变量
[edge_functions_environment]
  DIFY_API_KEY = "${DIFY_API_KEY}"
  DIFY_BASE_URL = "${DIFY_BASE_URL}"
  AZURE_SPEECH_KEY = "${AZURE_SPEECH_KEY}"
  AZURE_SPEECH_REGION = "${AZURE_SPEECH_REGION}"
  AZURE_SPEECH_VOICE = "${AZURE_SPEECH_VOICE}"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 为 VAD / onnxruntime-web 启用跨源隔离（SharedArrayBuffer 等能力）
[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "same-origin"


